apiVersion: naftiko.io/v1
kind: Capability
metadata:
  name: nyt-top-stories
  provider: new-york-times-company
  api: top-stories-api
  tags:
    - News
    - Top Stories
    - Sections
spec:
  summary: Retrieve current top stories for a NYTimes.com section.
  inputs:
    - name: section
      type: string
      required: true
      enum: [arts, automobiles, books, business, fashion, food, health, home, insider, magazine, movies, national, nyregion, obituaries, opinion, politics, realestate, science, sports, sundayreview, technology, theater, tmagazine, travel, upshot, world]
  outputs:
    - name: articles
      type: array
      itemsRef: openapi/top-stories-v2-openapi.yml#/definitions/Article
  operation:
    method: GET
    path: /{section}.json
    baseURL: https://api.nytimes.com/svc/topstories/v2
  auth:
    type: apiKey
    in: query
    name: api-key
